language: rust

matrix:
  include:
    # ------------------------------------------------------
    # Linux Xenial distributions, Various Python versions
    # Rust: Stable, Beta and Nightly
    # ------------------------------------------------------
    #

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Job 1: Xenial + Stable Rust + Python 3.4
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: xenial
      # Note: Python 3.4 needs to be installed
      # Note: Prints lots of warnings when installing numpy
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - gcc
            - python3.4
            - python3.4-dev
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PYTHON_VERSION=3.4
      rust: stable
      python: "3.4"

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Job 2: Xenial + Stable Rust + Python 3.6
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - gcc
            - python3.6
            - python3.6-dev
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PYTHON_VERSION=3.6
      rust: stable
      python: "3.6"

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Job 3: Xenial + Stable Rust + Python 2.7
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - gcc
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PYTHON_VERSION=2.7
      rust: stable
      python: "2.7"

    # ------------------------------------------------------
    # Linux Trusty distributions, Python 3.6 and 2.7
    # Stable Rust
    # ------------------------------------------------------
    #

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Job 4: Trusty + Stable Rust + Python 2.7
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - gcc
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PYTHON_VERSION=2.7
      rust: stable
      python: "2.7"

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Job 5: Trusty + Stable Rust + Python 3.6
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - gcc
            - python3.6
            - python3.6-dev
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PYTHON_VERSION=3.6
      rust: stable
      python: "3.6"

    # ------------------------------------------------------
    # OSX Darwin, Python 3.6 and 2.7
    # Stable Rust
    # ------------------------------------------------------
    #

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Job 6: OSX + Stable Rust + Python 2.7
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: osx
      env:
        - TARGET=i686-apple-darwin
        - PYTHON_VERSION=2.7
      rust: stable
      python: "2.7"

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Job 7: OSX + Stable Rust + Python 3.6
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: osx
      env:
        - TARGET=i686-apple-darwin
        - PYTHON_VERSION=3.6
      rust: stable
      # Note: Python 3.6 is available by default
      python: "3.6"



before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/196d37e7f965d6bd599d
    on_success: always   # options: [always|never|change] default: always
    on_failure: always   # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
