language: rust

matrix:
  include:

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # [Job 1] Xenial + Stable Rust + Python 3.6
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - gcc
            - python3.6
            - python3.6-dev
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PYTHON_VERSION=3.6
        - DO_DOCKER=0
      rust: stable
      python: "3.6"

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # [Job 2] Xenial, Test Docker
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: xenial
      services:
        - docker
      env:
        - DO_DOCKER=1


    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # [Job 3] Trusty + Stable Rust + Python 3.6
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - gcc
            - python3.6
            - python3.6-dev
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PYTHON_VERSION=3.6
        - DO_DOCKER=0
      rust: stable
      python: "3.6"


    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # [Job 4] OSX + Stable Rust + Python 3.6
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - os: osx
      env:
        - TARGET=i686-apple-darwin
        - PYTHON_VERSION=3.7.5
        - DO_DOCKER=0
      rust: stable
      python: "3.7.5"



before_install:
  - set -e
  - python3 --version

install:
  - bash ci/install.sh

before_script:
  - rustup component add clippy

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/196d37e7f965d6bd599d
    on_success: always   # options: [always|never|change] default: always
    on_failure: always
    on_start: always

