language: rust

matrix:
  include:
    # ------------------------------------------------------
    # Linux Xenial distributions, Various Python versions
    # Rust: Stable, Beta and Nightly
    # ------------------------------------------------------
    #
    - os: linux
      dist: xenial
      env: 
      - TARGET=x86_64-unknown-linux-gnu
      - PYTHON_VERSION=3.4
      rust: nightly
      python: "3.4"

    - os: linux
      dist: xenial
      env: 
      - TARGET=x86_64-unknown-linux-gnu
      - PYTHON_VERSION=3.6
      rust: beta
      python: "3.6"

    - os: linux
      dist: xenial
      env: 
      - TARGET=x86_64-unknown-linux-gnu
      - PYTHON_VERSION=3.6
      rust: stable
      python: "3.6"

    - os: linux
      dist: xenial
      env: 
      - TARGET=x86_64-unknown-linux-gnu
      - PYTHON_VERSION=2.7
      rust: stable
      python: "2.7"

    # ------------------------------------------------------
    # Linux Trusty distributions, Python 3.6 and 2.7
    # Stable Rust
    # ------------------------------------------------------
    # 
    - os: linux
      dist: trusty
      env: 
      - TARGET=x86_64-unknown-linux-gnu
      - PYTHON_VERSION=2.7
      rust: stable
      python: "2.7"

    - os: linux
      dist: trusty
      env: 
      - TARGET=x86_64-unknown-linux-gnu
      - PYTHON_VERSION=3.6
      rust: stable
      python: "3.6"

    # ------------------------------------------------------
    # OSX Darwin, Python 3.6 and 2.7
    # Stable Rust
    # ------------------------------------------------------
    #
    - os: osx
      env: 
      - TARGET=i686-apple-darwin
      - PYTHON_VERSION=2.7
      rust: stable
      python: "2.7"

    - os: linux
      env: 
      - TARGET=i686-apple-darwin
      - PYTHON_VERSION=3.6
      rust: stable
      python: "3.6"



before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/196d37e7f965d6bd599d
    on_success: always   # options: [always|never|change] default: always
    on_failure: always   # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
